steps:   
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['clean']
   
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['package']
 
 - name: "gcr.io/cloud-builders/gcloud"
   args: ["app", "deploy","src/main/appengine/app.yaml"]
   timeout: 2000s

timeout: 2000s
