steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['clean']
  
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['install']
   
 - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$_IMAGE_NAME", "--build-arg=WAR_FILE=target/springboot-0.0.1-SNAPSHOT.war", "."]
images: ["gcr.io/$PROJECT_ID/hellospring"]