apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: springdeploy
spec:
  selector:
    matchLabels:
      app: springapp
  replicas: 2 # It can be any number
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
      - name: springboot
        image: gcr.io/eternal-ship-281907/springapp:latest
        ports:
        - containerPort: 8080